twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic: /cmd_vel_teleop
        timeout: 0.5
        priority: 100
      nav:
        topic: /cmd_vel_nav
        timeout: 0.5
        priority: 50
